HospitalReview_rev9/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from utama import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^rumah_sakit/', include('rumah_sakit.urls')),
    url(r'^diagnosis/', include('diagnosis_penyakit.url')),
    url(r'^asuransi/', include('asuransi.urls')),
    url(r'^pengunjung/', include('pengunjung.urls')),
    url(r'^home/', include('utama.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^404/',views.Page404View.as_view(), name='not_found'),
    url(r'^403/',views.Page403View.as_view(), name='access_denied'),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pengunjung/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'pengunjung'

urlpatterns = [
    url(r'^$',views.HomeView.as_view(), name='home'),
    url(r'^pengunjung/list', views.PengunjungListView.as_view(), name='pengunjung_list'),
    url(r'^pengunjung/create', views.PengunjungCreateView.as_view(), name='pengunjung_create'),
    url(r'^pengunjung/detail/(?P<pk>\d+)/$', views.PengunjungDetailView.as_view(), name = 'pengunjung_detail'),
    url(r'^pengunjung/update/(?P<pk>\d+)/$', views.PengunjungUpdateView.as_view(), name = 'pengunjung_update'),
    url(r'^pengunjung/delete/(?P<pk>\d+)/$', views.PengunjungDeleteView.as_view(), name = 'pengunjung_delete'),
    url(r'^review/list', views.ReviewListView.as_view(), name='review_list'),
    url(r'^review/create', views.ReviewCreateView.as_view(), name='review_create'),
    url(r'^review/detail/(?P<pk>\d+)/$', views.ReviewDetailView.as_view(), name='review_detail'),
    url(r'^review/update/(?P<pk>\d+)/$', views.ReviewUpdateView.as_view(), name='review_update'),
    url(r'^review/delete/(?P<pk>\d+)/$', views.ReviewDeleteView.as_view(), name='review_delete'),
    url(r'^foto_review/list', views.FotoReviewListView.as_view(), name='foto_review_list'),
    url(r'^foto_review/create/', views.FotoReviewCreateView.as_view(), name='foto_review_create'),
    url(r'^foto_review/detail/(?P<pk>\d+)/$',views.FotoReviewDetailView.as_view(), name='foto_review_detail'),
    url(r'^foto_review/update/(?P<pk>\d+)/$',views.FotoReviewUpdateView.as_view(), name='foto_review_update'),
    url(r'^foto_review/delete/(?P<pk>\d+)/$',views.FotoReviewDeleteView.as_view(), name='foto_review_delete'),
    # url(r'^pengunjung/registrasi', views.RegistrasiAkun.as_view(), name='registrasi_pengunjung')
]

utama/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'utama'
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^login/',views.login_view, name='login'),
    url(r'^logout/',views.Logout.as_view(), name='logout'),

    url(r'^signup/pengunjung/', views.pengunjung_registrasi, name='pengunjung_registrasi'),
    url(r'^signup/dokter/', views.dokter_registrasi, name='dokter_registrasi'),
    url(r'^signup/asuransi/', views.asuransi_registrasi, name='asuransi_registrasi'),
    url(r'^signup/rumah_sakit/', views.rumah_sakit_registrasi, name='rumah_sakit_registrasi'),

    url(r'^pencarian/', views.PencarianListView.as_view(), name='pencarian_list'),

    url(r'^berita/list/', views.BeritaListView.as_view(), name='list'),
    url(r'^berita/create/',views.BeritaCreateView.as_view(), name='create'),
    url(r'^berita/detail/(?P<pk>\d+)/$',views.BeritaDetailView.as_view(), name='detail'),
    url(r'^berita/update/(?P<pk>\d+)/$', views.BeritaUpdateView.as_view(), name='update'),
    url(r'^berita/delete/(?P<pk>\d+)/$', views.BeritaDeleteView.as_view(), name='delete'),

    url(r'^admin/detail/(?P<pk>\d+)/$',views.AdministratorDetailView.as_view(), name='administrator_detail'),
    url(r'^admin/update/(?P<pk>\d+)/$',views.AdministratorUpdateView.as_view(), name='administrator_update'),

    url(r'^admin/hubungan_rumah_sakit_asuransi/request/list/$', views.PermintaanHubunganAsuransiListView.as_view(), name='hubungan_request'),
    url(r'^admin/hubungan_rumah_sakit_asuransi/all/list/$', views.HubunganRumahSakitAsuransiListView.as_view(), name='hubungan_all'),
    url(r'^admin/hubungan_rumah_sakit_asuransi/validated/$', views.ValidatedHubunganAsuransiView.as_view(), name='hubungan_validated'),
    url(r'^admin/hubungan_rumah_sakit_asuransi/rejected/$', views.RejectedHubunganAsuransiView.as_view(), name='hubungan_rejected'),
    url(r'^admin/review/request/list/$', views.PermintaanReviewListView.as_view(), name='review_request'),
    url(r'^admin/review/all/list/$', views.ReviewAllListView.as_view(), name='review_all'),
    url(r'^admin/review/validated/$', views.ValidatedReviewView.as_view(), name='review_validated'),
    url(r'^admin/review/rejected/$', views.RejectedReviewView.as_view(), name='review_rejected'),

    url(r'rumah_sakit/validated_and_rejected', views.RumahSakitValidatedAndRejected.as_view(), name='rumah_sakit_rejected_and_validated'),
    url(r'asuransi/validated_and_rejected', views.AsuransiValidatedAndRejected.as_view(), name='asuransi_rejected_and_validated'),
    url(r'pengunjung/validated_and_rejected', views.PengunjungValidatedAndRejected.as_view(), name='pengunjung_rejected_and_validated'),

    url(r'^validation/$', views.PengunjungValidationEmailView.as_view(), name='validation_email'),

    url(r'^pesan/list/', views.PesanListView.as_view(), name='pesan_list'),
    url(r'^pesan/create/',views.PesanCreateView.as_view(), name='pesan_create'),
    url(r'^pesan/detail/(?P<pk>\d+)/$',views.PesanDetailView.as_view(), name='pesan_detail'),

]

pengunjung/views.py
from django.shortcuts import render, redirect
from django.views.generic import (TemplateView, View, ListView,
                                  DetailView, FormView, DeleteView,
                                  UpdateView, CreateView)
from .models import (RumahSakit, Akun, Review,
                     Pengunjung, FotoReview)
from utama.models import Administrator
from extra_views import InlineFormSet, CreateWithInlinesView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime
from function import metadata_image

# Create your views here.

class HomeView(View):
    def get(self, request):
        return render(request, 'pengunjung/home.html')

class PengunjungListView(LoginRequiredMixin, ListView):
    login_url = 'utama:login'
    redirect_field_name = ''
    context_object_name = 'pengunjungs'
    model = Pengunjung
    template_name = 'pengunjung/pengunjung_list.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator' and request.session['role']!='pengunjung'):
            return redirect('not_found')
        if(request.session['role']=='pengunjung'):
            self.queryset = Pengunjung.objects.filter(pk=int(request.session['role_pk']))
        return super(PengunjungListView, self).get(request,*args,**kwargs)

class PengunjungCreateView(LoginRequiredMixin, CreateView):
    login_url = 'utama:login'
    redirect_field_name = ''
    template_name = 'pengunjung/pengunjung_form.html'
    model = Pengunjung
    fields = ('akun', 'nama', 'tempat_lahir', 'tanggal_lahir',
              'golongan_darah', 'provinsi', 'kabupaten_kota',
              'kelurahan', 'rt_rw', 'kode_pos', 'jenis_kelamin',
              'nomor_telepon', 'foto_profil')

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if(request.session['role']!='administrator'):
            return redirect('not_found')
        return super(PengunjungCreateView, self).get(request=request, *args, **kwargs)

class PengunjungDetailView(LoginRequiredMixin, DetailView):
    login_url = 'utama:login'
    redirect_field_name = ''
    model = Pengunjung
    template_name = 'pengunjung/pengunjung_detail.html'
    context_object_name = 'pengunjung_detail'

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if(request.session['role']!='administrator' and request.session['role']!='pengunjung'):
            return redirect('not_found')
        if (request.session['role'] == 'pengunjung' and int(kwargs[self.pk_url_kwarg]) != int(request.session['role_pk'])):
            return redirect('not_found')
        return super(PengunjungDetailView, self).get(request=request, *args, **kwargs)

class PengunjungUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'utama:login'
    redirect_field_name = ''
    template_name = 'pengunjung/pengunjung_form.html'
    fields = ('nama', 'tempat_lahir', 'tanggal_lahir',
              'golongan_darah', 'provinsi', 'kabupaten_kota',
              'kelurahan', 'rt_rw', 'kode_pos', 'jenis_kelamin',
              'nomor_telepon', 'foto_profil')
    model = Pengunjung

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if(request.session['role']!='administrator' and request.session['role']!='pengunjung'):
            return redirect('not_found')
        if (request.session['role'] == 'pengunjung' and int(kwargs[self.pk_url_kwarg]) != int(request.session['role_pk'])):
            return redirect('not_found')
        return super(PengunjungUpdateView, self).get(request=request, *args, **kwargs)

class PengunjungDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'utama:login'
    redirect_field_name = ''
    model = Pengunjung
    success_url = reverse_lazy('pengunjung:pengunjung_list')
    context_object_name = 'pengunjung'
    template_name = 'pengunjung/pengunjung_confirm_delete.html'

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if(request.session['role']!='administrator'):
            return redirect('not_found')

        return super(PengunjungDeleteView, self).get(request=request, *args, **kwargs)

class ReviewListView(LoginRequiredMixin, ListView):
    login_url = 'utama:login'
    redirect_field_name = ''
    context_object_name = 'reviews'
    model = Review
    template_name = 'review/review_list.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator' and request.session['role']!='pengunjung'):
            return redirect('not_found')
        if(request.session['role']=='pengunjung'):
            self.queryset = Review.objects.filter(pengunjung=int(request.session['role_pk']))
        return super(ReviewListView, self).get(request, *args, **kwargs)

class ReviewCreateView(LoginRequiredMixin, CreateView):
    login_url = 'utama:login'
    redirect_field_name = ''
    template_name = 'review/review_form.html'
    model = Review
    fields = ('isi_review', 'data_lokasi_pengunjung_lintang',
              'data_lokasi_pengunjung_bujur', 'rating')

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if(request.session['role']!='pengunjung'):
            return redirect('not_found')
        return super(ReviewCreateView, self).get(request=request, *args, **kwargs)

    def form_valid(self, form):
        if(RumahSakit.objects.filter(pk=int(self.request.GET['data'])) is None):
            raise form.ValidationError("You've been change data...")
        else:
            form.instance.rumah_sakit = RumahSakit.objects.get(pk=int(self.request.GET['data']))
            form.instance.pengunjung = Pengunjung.objects.get(pk=int(self.request.session['role_pk']))
            form.instance.waktu_validasi = datetime.datetime.now()

        return super(ReviewCreateView, self).form_valid(form)

class ReviewDetailView(LoginRequiredMixin, DetailView):
    login_url = 'utama:login'
    redirect_field_name = ''
    model = Review
    template_name = 'review/review_detail.html'
    context_object_name = 'review_detail'

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator' and request.session['role'] != 'pengunjung'):
            return redirect('not_found')
        # try:
        #     if (request.session['role'] == 'pengunjung'
        #         and int(kwargs[self.pk_url_kwarg]) != Review.objects.get(
        #             pengunjung=int(request.session['role_pk'])).pk):
        #         return redirect('not_found')
        # except Exception:
        #     return redirect('not_found')

        return super(ReviewDetailView, self).get(request=request, *args, **kwargs)

class ReviewUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'utama:login'
    redirect_field_name = ''
    template_name = 'review/review_form.html'
    fields = ('isi_review', 'data_lokasi_pengunjung_lintang',
              'data_lokasi_pengunjung_bujur', 'rating')
    model = Review

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator' and request.session['role'] != 'pengunjung'):
            return redirect('not_found')
        # try:
        #     if (request.session['role'] == 'pengunjung'
        #         and int(kwargs[self.pk_url_kwarg]) != Review.objects.get(
        #             pengunjung=int(request.session['role_pk'])).pk):
        #         return redirect('not_found')
        # except Exception:
        #     return redirect('not_found')

        return super(ReviewUpdateView, self).get(request=request, *args, **kwargs)

class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'utama:login'
    redirect_field_name = ''
    model = Review
    success_url = reverse_lazy('pengunjung:review_list')
    context_object_name = 'review'
    template_name = 'review/review_confirm_delete.html'

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator' and request.session['role'] != 'pengunjung'):
            return redirect('not_found')
        # try:
        #     if (request.session['role'] == 'pengunjung'
        #         and int(kwargs[self.pk_url_kwarg]) != Review.objects.get(
        #             pengunjung=int(request.session['role_pk'])).pk):
        #         return redirect('not_found')
        # except Exception:
        #     return redirect('not_found')

        return super(ReviewDeleteView, self).get(request=request, *args, **kwargs)

class FotoReviewListView(LoginRequiredMixin, ListView):
    login_url = 'utama:login'
    redirect_field_name = ''
    context_object_name = 'foto_reviews'
    model = FotoReview
    template_name = 'foto_review/foto_review_list.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator' and request.session['role'] != 'pengunjung'):

pengunjung/templates/review/review_confirm_delete.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="container">
    <h1>Delete {{ review.pengunjung.nama}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="delete">
        <a href="{% url 'pengunjung:review_detail' pk=review.pk %}" class="btn btn-default">Cancel</a>
    </form>
    </div>
{% endblock %}

pengunjung/templates/review/review_detail.html
{% extends 'base.html' %}

{% block body_block %}

    <div class="container">
    <h2>Review</h2>
        <hr/>
        <p>Pengunjung : {{ review_detail.pengunjung }}</p>
        <p>Rumah Sakit : {{ review_detail.rumah_sakit.nama }}</p>
        <p>Rating : {{ review_detail.rating }}</p>
        <p>{{ review_detail.isi_review }}</p>
    <hr/>
        <p>
            <a class="btn btn-warning" href="{% url 'pengunjung:review_update' pk=review_detail.pk %}">Update</a>
            <a class="btn btn-danger" href="{% url 'pengunjung:review_delete' pk=review_detail.pk %}">Delete</a>
        </p>
        <div class="navbar-right">
            <form action="{% url 'pengunjung:foto_review_create' %}" method="get">
                <input type="hidden" name="data" value="{{ review_detail.pk }}">
                <button class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Tambahkan Foto</button>
            </form>
        </div>
    </div>
{% endblock %}

pengunjung/templates/review/review_form.html
{% extends 'base.html' %}
{% load widget_tweaks  %}
{% block body_block %}
    <div class="container">
        <h2>Kelolah Review</h2>
        <hr/>
        <div class="row">
            <div class="col-lg-8">
                <form method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
{#                    {{ form.as_p }}#}
                    {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.name }}">{{ field.label }}</label>
                            {{ field | add_class:'form-control' }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <br/>
{% endblock %}

pengunjung/templates/review/review_list.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="container">
     <div class="row">
            <div class="col-lg-8">
                <h1>List Review</h1>
            </div>
            <div class="col-lg-4">
                {% if request.session.role == 'administrator'%}
                    <div class="navbar-right">
                        <p>Lihat Detail dan tambahkan foto review anda...

                                <a href="{% url 'pengunjung:foto_review_create' %}">
                                    {% if request.session.role == 'administrator' %}
                                        <br/>
                                        <button class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add Review</button>
                                    {% endif %}
                                </a>

                        </p>
                    </div>
                {% endif %}
            </div>
        </div>
        <hr/>

        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>Nama Pengunjung</th>
                    <th>Nama Rumah Sakit</th>
                    <th>Rating</th>
                    <th>Waktu Pembuatan</th>
                    <th>Status Validasi</th>
                </tr>
            </thead>
            <tbody>
                {% for foo in reviews %}
                    <tr>
                        <td><a href="detail/{{ foo.pk }}">{{ foo.pengunjung.nama }}</a></td>
                        <td>{{ foo.rumah_sakit.nama }}</td>
                        <td>{{ foo.rating }}</td>
                        <td>{{ foo.waktu_stamp }}</td>
                        <td>{{ foo.status_validasi }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <br/>
        <div class="text-center">
        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number  }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
        </div>
    </div>
{% endblock %}