HospitalReview_rev9/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from utama import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^rumah_sakit/', include('rumah_sakit.urls')),
    url(r'^diagnosis/', include('diagnosis_penyakit.url')),
    url(r'^asuransi/', include('asuransi.urls')),
    url(r'^pengunjung/', include('pengunjung.urls')),
    url(r'^home/', include('utama.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^404/',views.Page404View.as_view(), name='not_found'),
    url(r'^403/',views.Page403View.as_view(), name='access_denied'),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

asuransi/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'asuransi'

urlpatterns = [
    url(r'^$',views.HomeView.as_view(), name='home'),
    url(r'^asuransi/list', views.AsuransiListView.as_view(), name='asuransi_list'),
    url(r'^asuransi/create', views.AsuransiCreateView.as_view(), name='asuransi_create'),
    url(r'^asuransi/detail/(?P<pk>\d+)/$', views.AsuransiDetailView.as_view(), name='asuransi_detail'),
    url(r'^asuransi/update/(?P<pk>\d+)/$', views.AsuransiUpdateView.as_view(), name='asuransi_update'),
    url(r'^asuransi/delete/(?P<pk>\d+)/$', views.AsuransiDeleteView.as_view(), name='asuransi_delete'),
    url(r'^hubungan_rumah_sakit_asuransi/list', views.HubunganRumahSakitAsuransiListView.as_view(),
        name='hubungan_rumah_sakit_asuransi_list'),
    url(r'^hubungan_rumah_sakit_asuransi/create', views.HubunganRumahSakitAsuransiCreateView.as_view(),
        name='hubungan_rumah_sakit_asuransi_create'),
    url(r'^hubungan_rumah_sakit_asuransi/detail/(?P<pk>\d+)/$',views.HubunganRumahSakitAsuransiDetailView.as_view(),
        name='hubungan_rumah_sakit_asuransi_detail'),
    url(r'^hubungan_rumah_sakit_asuransi/update/(?P<pk>\d+)/$',views.HubunganRumahSakitAsuransiUpdateView.as_view(),
            name='hubungan_rumah_sakit_asuransi_update'),
    url(r'^hubungan_rumah_sakit_asuransi/delete/(?P<pk>\d+)/$',views.HubunganRumahSakitAsuransiDeleteView.as_view(),
            name='hubungan_rumah_sakit_asuransi_delete'),
]

utama/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'utama'
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^login/',views.login_view, name='login'),
    url(r'^logout/',views.Logout.as_view(), name='logout'),

    url(r'^signup/pengunjung/', views.pengunjung_registrasi, name='pengunjung_registrasi'),
    url(r'^signup/dokter/', views.dokter_registrasi, name='dokter_registrasi'),
    url(r'^signup/asuransi/', views.asuransi_registrasi, name='asuransi_registrasi'),
    url(r'^signup/rumah_sakit/', views.rumah_sakit_registrasi, name='rumah_sakit_registrasi'),

    url(r'^pencarian/', views.PencarianListView.as_view(), name='pencarian_list'),

    url(r'^berita/list/', views.BeritaListView.as_view(), name='list'),
    url(r'^berita/create/',views.BeritaCreateView.as_view(), name='create'),
    url(r'^berita/detail/(?P<pk>\d+)/$',views.BeritaDetailView.as_view(), name='detail'),
    url(r'^berita/update/(?P<pk>\d+)/$', views.BeritaUpdateView.as_view(), name='update'),
    url(r'^berita/delete/(?P<pk>\d+)/$', views.BeritaDeleteView.as_view(), name='delete'),

    url(r'^admin/detail/(?P<pk>\d+)/$',views.AdministratorDetailView.as_view(), name='administrator_detail'),
    url(r'^admin/update/(?P<pk>\d+)/$',views.AdministratorUpdateView.as_view(), name='administrator_update'),

    url(r'^admin/hubungan_rumah_sakit_asuransi/request/list/$', views.PermintaanHubunganAsuransiListView.as_view(), name='hubungan_request'),
    url(r'^admin/hubungan_rumah_sakit_asuransi/all/list/$', views.HubunganRumahSakitAsuransiListView.as_view(), name='hubungan_all'),
    url(r'^admin/hubungan_rumah_sakit_asuransi/validated/$', views.ValidatedHubunganAsuransiView.as_view(), name='hubungan_validated'),
    url(r'^admin/hubungan_rumah_sakit_asuransi/rejected/$', views.RejectedHubunganAsuransiView.as_view(), name='hubungan_rejected'),
    url(r'^admin/review/request/list/$', views.PermintaanReviewListView.as_view(), name='review_request'),
    url(r'^admin/review/all/list/$', views.ReviewAllListView.as_view(), name='review_all'),
    url(r'^admin/review/validated/$', views.ValidatedReviewView.as_view(), name='review_validated'),
    url(r'^admin/review/rejected/$', views.RejectedReviewView.as_view(), name='review_rejected'),

    url(r'rumah_sakit/validated_and_rejected', views.RumahSakitValidatedAndRejected.as_view(), name='rumah_sakit_rejected_and_validated'),
    url(r'asuransi/validated_and_rejected', views.AsuransiValidatedAndRejected.as_view(), name='asuransi_rejected_and_validated'),
    url(r'pengunjung/validated_and_rejected', views.PengunjungValidatedAndRejected.as_view(), name='pengunjung_rejected_and_validated'),

    url(r'^validation/$', views.PengunjungValidationEmailView.as_view(), name='validation_email'),

    url(r'^pesan/list/', views.PesanListView.as_view(), name='pesan_list'),
    url(r'^pesan/create/',views.PesanCreateView.as_view(), name='pesan_create'),
    url(r'^pesan/detail/(?P<pk>\d+)/$',views.PesanDetailView.as_view(), name='pesan_detail'),

]

asuransi/models.py
from django.db import models
from utama.models import Administrator, Akun
from rumah_sakit.models import RumahSakit
from django.urls import reverse

# Create your models here.

class Asuransi(models.Model):
    """docstring for Asuransi."""
    STATUS_CHOICES = (
        ('rejected', 'Rejected'),
        ('validated', 'Validated'),
        ('request', 'Request')
    )

    akun = models.ForeignKey(Akun, related_name='asuransis', on_delete=models.CASCADE)
    nama = models.CharField(max_length=100, unique=True)
    url_website = models.CharField(max_length=400)
    dokumen = models.FileField(upload_to='dokumen_asuransi', blank=True)
    foto_profil = models.ImageField(upload_to='foto_profil_asuransi', blank=True)
    nomor_telepon = models.CharField(max_length=20)
    status_validasi = models.CharField(max_length=50, choices=STATUS_CHOICES, default='request')
    waktu_validasi = models.DateTimeField(blank=True, null=True)
    administrator = models.ForeignKey(Administrator, blank=True, null=True, default=1, related_name='asuransis', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('asuransi:asuransi_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.nama


class HubunganRumahSakitAsuransi(models.Model):
    """docstring for HubunganRumahSakitAsuransi."""
    STATUS_CHOICES = (
        ('rejected', 'Rejected'),
        ('validated', 'Validated'),
        ('request', 'Request')
    )

    asuransi = models.ForeignKey(Asuransi, related_name='hubungan_rumah_sakit_asuransis', on_delete=models.CASCADE)
    rumah_sakit = models.ForeignKey(RumahSakit, related_name='hubungan_rumah_sakit_asuransis', on_delete=models.CASCADE)
    dokumen = models.FileField(upload_to='dokumen_hubungan_rumah_sakit_asuransi', blank=True)
    administrator = models.ForeignKey(Administrator, related_name='hubungan_rumah_sakit_asuransis', null=True, on_delete=models.CASCADE)
    status_validasi_rumah_sakit = models.CharField(max_length=50, choices=STATUS_CHOICES, default='request')
    status_validasi_administrator = models.CharField(max_length=50, choices=STATUS_CHOICES, default='request')
    waktu_validasi = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('asuransi:hubungan_rumah_sakit_asuransi_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.rumah_sakit.nama + ' - ' + self.asuransi.nama

asuransi/views.py
from django.shortcuts import render, redirect
from django.views.generic import (TemplateView, View, ListView,
                                  DetailView, FormView, DeleteView,
                                  UpdateView, CreateView)
from .models import (Akun, Asuransi, Administrator,
                     RumahSakit, HubunganRumahSakitAsuransi)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime
# Create your views here.

class HomeView(View):
    def get(self, request):
        return render(request, 'asuransi/home.html')

class AsuransiListView(LoginRequiredMixin, ListView):
    login_url = 'utama:login'
    redirect_field_name = ''
    context_object_name = 'asuransis'
    model = Asuransi
    template_name = 'asuransi/asuransi_list.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator'):
            return redirect('not_found')
        return super(AsuransiListView, self).get(request,*args,**kwargs)

class AsuransiCreateView(LoginRequiredMixin, CreateView):
    login_url = 'utama:login'
    redirect_field_name = ''
    template_name = 'asuransi/asuransi_form.html'
    model = Asuransi
    fields = ('akun', 'nama', 'url_website',
              'dokumen', 'foto_profil', 'nomor_telepon',
              'status_validasi', 'waktu_validasi', 'administrator')

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if(request.session['role']!='administrator'):
            return redirect('not_found')
        return super(AsuransiCreateView, self).get(request=request, *args, **kwargs)

class AsuransiDetailView(LoginRequiredMixin, DetailView):
    login_url = 'utama:login'
    redirect_field_name = ''
    model = Asuransi
    template_name = 'asuransi/asuransi_detail.html'
    context_object_name = 'asuransi_detail'

    def get(self, request, *args, **kwargs):
        if(request.session['role']!='administrator' and request.session['role']!='asuransi'):
            return redirect('not_found')
        if (request.session['role'] == 'asuransi' and int(kwargs[self.pk_url_kwarg]) != int(request.session['role_pk'])):
            return redirect('not_found')
        return super(AsuransiDetailView, self).get(request=request, *args, **kwargs)

class AsuransiUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'utama:login'
    redirect_field_name = ''
    template_name = 'asuransi/asuransi_form.html'
    fields = ('nama', 'url_website',
              'dokumen', 'foto_profil', 'nomor_telepon')
    model = Asuransi

    def get(self, request, *args, **kwargs):
        if(request.session['role']!='administrator' and request.session['role']!='asuransi'):
            return redirect('not_found')
        if (request.session['role'] == 'asuransi' and int(kwargs[self.pk_url_kwarg]) != int(request.session['role_pk'])):
            return redirect('not_found')
        return super(AsuransiUpdateView, self).get(request=request, *args, **kwargs)

class AsuransiDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'utama:login'
    redirect_field_name = ''
    model = Asuransi
    success_url = reverse_lazy('asuransi:asuransi_list')
    context_object_name = 'asuransi'
    template_name = 'asuransi/asuransi_confirm_delete.html'

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if(request.session['role']!='administrator'):
            return redirect('not_found')
        return super(AsuransiDeleteView, self).get(request=request, *args, **kwargs)

class HubunganRumahSakitAsuransiListView(LoginRequiredMixin, ListView):
    login_url = 'utama:login'
    redirect_field_name = ''
    context_object_name = 'hubungan_rumah_sakit_asuransis'
    model = HubunganRumahSakitAsuransi
    template_name = 'hubungan_rumah_sakit_asuransi/hubungan_rumah_sakit_asuransi_list.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator' and request.session['role']!='asuransi'):
            return redirect('not_found')
        if(request.session['role']=='asuransi'):
            self.queryset = HubunganRumahSakitAsuransi.objects.filter(asuransi=int(request.session['role_pk']))
        return super(HubunganRumahSakitAsuransiListView, self).get(request, *args, **kwargs)

class HubunganRumahSakitAsuransiCreateView(LoginRequiredMixin, CreateView):
    login_url = 'utama:login'
    redirect_field_name = ''
    template_name = 'hubungan_rumah_sakit_asuransi/hubungan_rumah_sakit_asuransi_form.html'
    model = HubunganRumahSakitAsuransi
    fields = ('rumah_sakit', 'dokumen')

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if(request.session['role']!='asuransi'):
            return redirect('not_found')
        return super(HubunganRumahSakitAsuransiCreateView, self).get(request=request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.asuransi = Asuransi.objects.get(pk = self.request.session['role_pk'])
        form.instance.administrator = Administrator.objects.get(pk=1)
        form.instance.status_validasi_rumah_sakit = 'request'
        form.instance.status_validasi_administrator = 'request'
        form.instance.waktu_validasi = datetime.datetime.now()

        return super(HubunganRumahSakitAsuransiCreateView, self).form_valid(form)

class HubunganRumahSakitAsuransiDetailView(LoginRequiredMixin, DetailView):
    login_url = 'utama:login'
    redirect_field_name = ''
    model = HubunganRumahSakitAsuransi
    template_name = 'hubungan_rumah_sakit_asuransi/hubungan_rumah_sakit_asuransi_detail.html'
    context_object_name = 'hubungan_rumah_sakit_asuransi_detail'

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator' and request.session['role'] != 'asuransi'):
            return redirect('not_found')
        # try:
        #     if (request.session['role'] == 'asuransi'
        #         and int(kwargs[self.pk_url_kwarg]) != HubunganRumahSakitAsuransi.objects.get(
        #             asuransi=int(request.session['role_pk'])).pk):
        #         return redirect('not_found')
        # except Exception:
        #     return redirect('not_found')

        return super(HubunganRumahSakitAsuransiDetailView, self).get(request=request, *args, **kwargs)

class HubunganRumahSakitAsuransiUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'utama:login'
    redirect_field_name = ''
    template_name = 'hubungan_rumah_sakit_asuransi/hubungan_rumah_sakit_asuransi_form.html'
    fields = ('dokumen',)
    model = HubunganRumahSakitAsuransi

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator' and request.session['role'] != 'asuransi'):
            return redirect('not_found')
        # try:
        #     if (request.session['role'] == 'asuransi'
        #         and int(kwargs[self.pk_url_kwarg]) != HubunganRumahSakitAsuransi.objects.get(
        #             asuransi=int(request.session['role_pk'])).pk):
        #         return redirect('not_found')
        # except Exception:
        #     return redirect('not_found')

        return super(HubunganRumahSakitAsuransiUpdateView, self).get(request=request, *args, **kwargs)

class HubunganRumahSakitAsuransiDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'utama:login'
    redirect_field_name = ''
    model = HubunganRumahSakitAsuransi
    success_url = reverse_lazy('asuransi:hubungan_rumah_sakit_asuransi_list')
    context_object_name = 'hubungan_rumah_sakit_asuransi'
    template_name = 'hubungan_rumah_sakit_asuransi/hubungan_rumah_sakit_asuransi_confirm_delete.html'

    def get(self, request, *args, **kwargs):
        if (not (request.session['status'] == 'validated')):
            return redirect('access_denied')
        if (request.session['role'] != 'administrator' and request.session['role'] != 'asuransi'):
            return redirect('not_found')
        # try:
        #     if (request.session['role'] == 'asuransi'
        #         and int(kwargs[self.pk_url_kwarg]) != HubunganRumahSakitAsuransi.objects.get(
        #             asuransi=int(request.session['role_pk'])).pk):
        #         return redirect('not_found')
        # except Exception:
        #     return redirect('not_found')

        return super(HubunganRumahSakitAsuransiDeleteView, self).get(request=request, *args, **kwargs)

asuransi/templates/asuransi/asuransi_confirm_delete.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="container">
    <h1>Delete {{ asuransi.nama }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="delete">
        <a href="{% url 'asuransi:asuransi_detail' pk=asuransi.pk %}" class="btn btn-default">Cancel</a>
    </form>
    </div>
{% endblock %}

asuransi/templates/asuransi/asuransi_detail.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="container">
        <h2>Asuransi</h2>
        <hr/>
        <h3>{{ asuransi_detail.nama }}</h3>
        <div class="row">
            <div class="col-lg-5">
                <img src="{{ asuransi_detail.foto_profil.url }}" alt="Picture Not Available" width="500em" height="500em" class="img-thumbnail">
            </div>
            <div class="col-lg-6">
                <p>Nama Asuransi : {{ asuransi_detail.nama }}</p>
                <p>Nomor Telepon : {{ asuransi_detail.nomor_telepon }}</p>
                <p>Url Website : {{ asuransi_detail.url_website }}</p>
                <p>Status  Validasi : {{ asuransi_detail.status_validasi }}</p>
                <p>Dokumen Terkait : <a href="{{ asuransi_detail.dokumen.url }}">{{ asuransi_detail.dokumen.name }}</a></p>
             </div>
        </div>
        <hr/>
        {% if request.session.role == 'administrator' or request.session.role == 'asuransi' %}
            <p>
                <a class="btn btn-warning" href="{% url 'asuransi:asuransi_update' pk=asuransi_detail.pk %}">Update</a>
                {% if request.session.role == 'administrator' %}
                    <a class="btn btn-danger" href="{% url 'asuransi:asuransi_delete' pk=asuransi_detail.pk %}">Delete</a>
                {% endif %}
            </p>
        {% endif %}
        <br/>

		<h3>Rumah Sakit Terkait</h3>
        <hr/>
        <table class="table">
            <thead>
                <tr>
                    <th>Nama Rumah Sakit</th>
                </tr>
            </thead>
            <tbody>
                {% for hubungan_rumah_sakit_asuransi in asuransi_detail.hubungan_rumah_sakit_asuransis.all %}
                    <tr>
                        {% if hubungan_rumah_sakit_asuransi.status_validasi_rumah_sakit == 'validated' and hubungan_rumah_sakit_asuransi.status_validasi_asuransi == 'validated' %}
                            <td>{{ hubungan_rumah_sakit_asuransi.rumah_sakit }}</td>
                        {% endif %}
{#                        <td>{{ hubungan_rumah_sakit_asuransi.rumah_sakit }}</td>#}
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

asuransi/templates/asuransi/asuransi_form.html
{% extends 'base.html' %}
{% load widget_tweaks  %}
{% block body_block %}
    <div class="container">
        <h2>Kelolah Asuransi</h2>
        <hr/>
        <div class="row">
            <div class="col-lg-8">
                <form method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
{#                    {{ form.as_p }}#}
                    {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.name }}">{{ field.label }}</label>
                            {{ field | add_class:'form-control' }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <br/>
{% endblock %}

asuransi/templates/asuransi/asuransi_list.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="container">
     <div class="row">
            <div class="col-lg-8">
                <h1>List Asuransi</h1>
            </div>
            <div class="col-lg-4">
                {% if request.session.role == 'administrator' %}
                     <div class="navbar-right">
                        <a href="{% url 'asuransi:asuransi_create' %}">
                            <button class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add Asuransi</button>
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
        <hr/>

        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>Nama Auransi</th>
                    <th>Nomor Telepon</th>
                    <th>Url Website</th>
                    {% if request.session.role == 'administrator'%}
                        <th>Dokumen Terkait</th>
                        <th>Status Validasi</th>
                        <th>Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for foo in asuransis %}
                    <tr>
                        <td><a href="detail/{{ foo.pk }}">{{ foo.nama }}</a></td>
                        <td>{{ foo.nomor_telepon }}</td>
                        <td>{{ foo.url_website }}</td>
                        {% if request.session.role == 'administrator'%}
                            <td>
                                <a href="{{ foo.dokumen.url }}">dokumen</a>
                            </td>
                            <td>
                                {{ foo.status_validasi }}
                            </td>
                            {% if foo.status_validasi == 'request' and request.session.role == 'administrator'%}
                                <td>
                                    <a href="{% url 'utama:asuransi_rejected_and_validated' %}?submit={{ foo.pk }}&status=validated">
                                        <button class="btn btn-success">Validated</button>
                                    </a>
                                    <a href="{% url 'utama:asuransi_rejected_and_validated' %}?submit={{ foo.pk }}&status=rejected">
                                        <button class="btn btn-danger">Rejected</button>
                                    </a>
                                </td>
                            {% else %}
                                <td>
                                    No Action Available
                                </td>
                            {% endif %}
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="text-center">
        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number  }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
        </div>
    </div>
{% endblock %}

asuransi/templates/asuransi/home.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="container">
    Home Asuransi
    </div>
{% endblock %}