HospitalReview_rev9/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from utama import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^rumah_sakit/', include('rumah_sakit.urls')),
    url(r'^diagnosis/', include('diagnosis_penyakit.url')),
    url(r'^asuransi/', include('asuransi.urls')),
    url(r'^pengunjung/', include('pengunjung.urls')),
    url(r'^home/', include('utama.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^404/',views.Page404View.as_view(), name='not_found'),
    url(r'^403/',views.Page403View.as_view(), name='access_denied'),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rumah_sakit/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'rumah_sakit'

urlpatterns = [
    url(r'^$',views.RumahSakitHomeView.as_view(), name='home'),
    url(r'^rumah_sakit/list', views.RumahSakitListView.as_view(), name='rumah_sakit_list'),
    url(r'^rumah_sakit/create',views.RumahSakitCreateView.as_view(), name='rumah_sakit_create'),
    url(r'^rumah_sakit/detail/(?P<pk>\d+)/$',views.RumahSakitDetailView.as_view(), name='rumah_sakit_detail'),
    url(r'^rumah_sakit/detail/peta',views.RumahSakitLihatPetaView.as_view(), name='lihat_peta_rumah_sakit'),
    url(r'^rumah_sakit/update/(?P<pk>\d+)/$',views.RumahSakitUpdateView.as_view(), name='rumah_sakit_update'),
    url(r'^rumah_sakit/delete/(?P<pk>\d+)/$',views.RumahSakitDeleteView.as_view(), name='rumah_sakit_delete'),

    url(r'^foto_rumah_sakit/list', views.FotoRumahSakitListView.as_view(), name='foto_rumah_sakit_list'),
    url(r'^foto_rumah_sakit/create', views.FotoRumahSakitCreateView.as_view(), name='foto_rumah_sakit_create'),
    url(r'^foto_rumah_sakit/detail/(?P<pk>\d+)/$', views.FotoRumahSakitDetailView.as_view(), name='foto_rumah_sakit_detail'),
    url(r'^foto_rumah_sakit/update/(?P<pk>\d+)/$', views.FotoRumahSakitUpdateView.as_view(), name='foto_rumah_sakit_update'),
    url(r'^foto_rumah_sakit/delete/(?P<pk>\d+)/$', views.FotoRumahSakitDeleteView.as_view(), name='foto_rumah_sakit_delete'),

    url(r'^jenis_fasilitas/list',views.JenisFasilitasListView.as_view(), name='jenis_fasilitas_list'),
    url(r'^jenis_fasilitas/create',views.JenisFasilitasCreateView.as_view(), name='jenis_fasilitas_create'),
    url(r'^jenis_fasilitas/detail/(?P<pk>\d+)/$', views.JenisFasilitasDetailView.as_view(), name='jenis_fasilitas_detail'),
    url(r'^jenis_fasilitas/update/(?P<pk>\d+)/$', views.JenisFasilitasUpdateView.as_view(), name='jenis_fasilitas_update'),
    url(r'^jenis_fasilitas/delete/(?P<pk>\d+)/$', views.JenisFasilitasDeleteView.as_view(), name='jenis_fasilitas_delete'),

    url(r'^fasilitas_rumah_sakit/list', views.FasilitasRumahSakitListView.as_view(), name='fasilitas_rumah_sakit_list'),
    url(r'^fasilitas_rumah_sakit/create', views.FasilitasRumahSakitCreateView.as_view(), name='fasilitas_rumah_sakit_create'),
    url(r'^fasilitas_rumah_sakit/detail/(?P<pk>\d+)/$', views.FasilitasRumahSakitDetailView.as_view(), name='fasilitas_rumah_sakit_detail'),
    url(r'^fasilitas_rumah_sakit/update/(?P<pk>\d+)/$', views.FasilitasRumahSakitUpdateView.as_view(), name='fasilitas_rumah_sakit_update'),
    url(r'^fasilitas_rumah_sakit/delete/(?P<pk>\d+)/$', views.FasilitasRumahSakitDeleteView.as_view(), name='fasilitas_rumah_sakit_delete'),

    url(r'^spesialis/list', views.SpesialisListView.as_view(), name='spesialis_list'),
    url(r'^spesialis/create', views.SpesialisCreateView.as_view(), name='spesialis_create'),
    url(r'^spesialis/detail/(?P<pk>\d+)/$', views.SpesialisDetailView.as_view(), name='spesialis_detail'),
    url(r'^spesialis/update/(?P<pk>\d+)/$', views.SpesialisUpdateView.as_view(), name='spesialis_update'),
    url(r'^spesialis/delete/(?P<pk>\d+)/$', views.SpesialisDeleteView.as_view(), name='spesialis_delete'),

    url(r'^dokter/list', views.DokterListView.as_view(), name='dokter_list'),
    url(r'^dokter/create', views.DokterCreateView.as_view(), name='dokter_create'),
    url(r'^dokter/detail/(?P<pk>\d+)/$', views.DokterDetailView.as_view(), name='dokter_detail'),
    url(r'^dokter/update/(?P<pk>\d+)/$', views.DokterUpdateView.as_view(), name='dokter_update'),
    url(r'^dokter/delete/(?P<pk>\d+)/$', views.DokterDeleteView.as_view(), name='dokter_delete'),

    url(r'^jadwal_dokter/list', views.JadwalDokterListView.as_view(), name='jadwal_dokter_list'),
    url(r'^jadwal_dokter/create', views.JadwalDokterCreateView.as_view(), name='jadwal_dokter_create'),
    url(r'^jadwal_dokter/detail/(?P<pk>\d+)/$', views.JadwalDokterDetailView.as_view(), name='jadwal_dokter_detail'),
    url(r'^jadwal_dokter/update/(?P<pk>\d+)/$', views.JadwalDokterUpdateView.as_view(), name='jadwal_dokter_update'),
    url(r'^jadwal_dokter/delete/(?P<pk>\d+)/$', views.JadwalDokterDeleteView.as_view(), name='jadwal_dokter_delete'),

    url(r'^penyakit/list', views.PenyakitListView.as_view(), name='penyakit_list'),
    url(r'^penyakit/create', views.PenyakitCreateView.as_view(), name='penyakit_create'),
    url(r'^penyakit/detail/(?P<pk>\d+)/$', views.PenyakitDetailView.as_view(), name='penyakit_detail'),
    url(r'^penyakit/update/(?P<pk>\d+)/$', views.PenyakitUpdateView.as_view(), name='penyakit_update'),
    url(r'^penyakit/delete/(?P<pk>\d+)/$', views.PenyakitDeleteView.as_view(), name='penyakit_delete'),

    url(r'^asuransi/validated/list', views.AsuransiTerkaitValidatedListView.as_view(), name='asuransi_validated_list'),
    url(r'^asuransi/request/list', views.PermintaanHubunganAsuransiListView.as_view(), name='asuransi_request_list'),
    url(r'^asuransi/validated/$',views.ValidatedHubunganAsuransiView.as_view(), name='validated_hubungan_asuransi_by_rumah_sakit'),
    url(r'^asuransi/rejected/$',views.RejectedHubunganAsuransiView.as_view(), name='rejected_hubungan_asuransi_by_rumah_sakit'),

    url(r'^test', views.test, name='test'),
]

utama/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'utama'
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^login/',views.login_view, name='login'),
    url(r'^logout/',views.Logout.as_view(), name='logout'),

    url(r'^signup/pengunjung/', views.pengunjung_registrasi, name='pengunjung_registrasi'),
    url(r'^signup/dokter/', views.dokter_registrasi, name='dokter_registrasi'),
    url(r'^signup/asuransi/', views.asuransi_registrasi, name='asuransi_registrasi'),
    url(r'^signup/rumah_sakit/', views.rumah_sakit_registrasi, name='rumah_sakit_registrasi'),

    url(r'^pencarian/', views.PencarianListView.as_view(), name='pencarian_list'),

    url(r'^berita/list/', views.BeritaListView.as_view(), name='list'),
    url(r'^berita/create/',views.BeritaCreateView.as_view(), name='create'),
    url(r'^berita/detail/(?P<pk>\d+)/$',views.BeritaDetailView.as_view(), name='detail'),
    url(r'^berita/update/(?P<pk>\d+)/$', views.BeritaUpdateView.as_view(), name='update'),
    url(r'^berita/delete/(?P<pk>\d+)/$', views.BeritaDeleteView.as_view(), name='delete'),

    url(r'^admin/detail/(?P<pk>\d+)/$',views.AdministratorDetailView.as_view(), name='administrator_detail'),
    url(r'^admin/update/(?P<pk>\d+)/$',views.AdministratorUpdateView.as_view(), name='administrator_update'),

    url(r'^admin/hubungan_rumah_sakit_asuransi/request/list/$', views.PermintaanHubunganAsuransiListView.as_view(), name='hubungan_request'),
    url(r'^admin/hubungan_rumah_sakit_asuransi/all/list/$', views.HubunganRumahSakitAsuransiListView.as_view(), name='hubungan_all'),
    url(r'^admin/hubungan_rumah_sakit_asuransi/validated/$', views.ValidatedHubunganAsuransiView.as_view(), name='hubungan_validated'),
    url(r'^admin/hubungan_rumah_sakit_asuransi/rejected/$', views.RejectedHubunganAsuransiView.as_view(), name='hubungan_rejected'),
    url(r'^admin/review/request/list/$', views.PermintaanReviewListView.as_view(), name='review_request'),
    url(r'^admin/review/all/list/$', views.ReviewAllListView.as_view(), name='review_all'),
    url(r'^admin/review/validated/$', views.ValidatedReviewView.as_view(), name='review_validated'),
    url(r'^admin/review/rejected/$', views.RejectedReviewView.as_view(), name='review_rejected'),

    url(r'rumah_sakit/validated_and_rejected', views.RumahSakitValidatedAndRejected.as_view(), name='rumah_sakit_rejected_and_validated'),
    url(r'asuransi/validated_and_rejected', views.AsuransiValidatedAndRejected.as_view(), name='asuransi_rejected_and_validated'),
    url(r'pengunjung/validated_and_rejected', views.PengunjungValidatedAndRejected.as_view(), name='pengunjung_rejected_and_validated'),

    url(r'^validation/$', views.PengunjungValidationEmailView.as_view(), name='validation_email'),

    url(r'^pesan/list/', views.PesanListView.as_view(), name='pesan_list'),
    url(r'^pesan/create/',views.PesanCreateView.as_view(), name='pesan_create'),
    url(r'^pesan/detail/(?P<pk>\d+)/$',views.PesanDetailView.as_view(), name='pesan_detail'),

]

rumah_sakit/models.py
from django.db import models
from utama.models import Administrator, Akun, User
from django.urls import reverse

# Create your models here.
class RumahSakit(models.Model):
    """docstring for RumahSakit."""
    STATUS_CHOICES = (
        ('request','Request'),
        ('validated','Validated'),
        ('rejected','Rejected')
    )

    STATUS_CHOICES_KELAS = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C')
    )

    nama = models.CharField(max_length=100)
    akun = models.ForeignKey(Akun, on_delete=models.CASCADE)
    foto_profil = models.ImageField(upload_to='foto_profil_rumah_sakit', blank=True)
    dokumen = models.FileField(upload_to='dokumen_rumah_sakit', blank=True)
    url_website = models.CharField(max_length=400, null=True)
    provinsi = models.CharField(max_length=100)
    kabupaten_kota = models.CharField(max_length=100)
    kecamatan = models.CharField(max_length=100)
    jalan = models.CharField(max_length=100, null=True)
    kode_pos = models.CharField(max_length=100, null=True)
    fax = models.CharField(max_length=40, null= True)
    nomor_telepon = models.CharField(max_length=20, null=True)
    lokasi_rumah_sakit_lintang = models.CharField(max_length=100, default='', null= True)
    lokasi_rumah_sakit_bujur = models.CharField(max_length=100, default='', null=True)
    status_validasi = models.CharField(max_length=20, choices=STATUS_CHOICES, default='request')
    waktu_validasi = models.DateField(blank=True, null=True)
    administrator = models.ForeignKey(Administrator,blank=True, null=True, related_name='rumah_sakits', on_delete=models.CASCADE)
    kelas = models.CharField(max_length=3, choices=STATUS_CHOICES_KELAS, blank=True, null=True)

    class Meta:
        ordering = ('kelas',)

    def get_absolute_url(self):
        return reverse('rumah_sakit:rumah_sakit_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.nama

class FotoRumahSakit(models.Model):
    """docstring for FotoRumahSakit."""
    rumah_sakit = models.ForeignKey(RumahSakit, related_name='foto_rumah_sakits', on_delete=models.CASCADE)
    foto_rumah_sakit = models.ImageField(upload_to='foto_rumah_sakit', blank=True)

    def get_absolute_url(self):
        return reverse('rumah_sakit:foto_rumah_sakit_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.rumah_sakit.nama

class JenisFasilitas(models.Model):
    """docstring for Fasilitas."""
    fasilitas = models.CharField(max_length=300)
    deskripsi = models.TextField()

    def get_absolute_url(self):
        return reverse('rumah_sakit:jenis_fasilitas_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.fasilitas

class FasilitasRumahSakit(models.Model):
    """docstring for FasilitasRumahSakit."""
    jenis_fasilitas = models.ForeignKey(JenisFasilitas, related_name='fasilitas_rumah_sakits', on_delete=models.CASCADE)
    rumah_sakit = models.ForeignKey(RumahSakit, related_name='fasilitas_rumah_sakits', on_delete=models.CASCADE)
    sub_fasilitas = models.CharField(max_length=200)
    jumlah = models.PositiveIntegerField()
    deskripsi = models.TextField()

    def get_absolute_url(self):
        return reverse('rumah_sakit:fasilitas_rumah_sakit_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.rumah_sakit.nama

class Spesialis(models.Model):
    """docstring for Spesialis."""
    jenis_spesialis = models.CharField(max_length=200)
    deskripsi = models.TextField()

    def get_absolute_url(self):
        return reverse('rumah_sakit:spesialis_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.jenis_spesialis

class Dokter(models.Model):
    """docstring for Dokter."""
    nama = models.CharField(max_length=100)
    email = models.EmailField(null=True)
    nomor_telepon = models.CharField(max_length=20, null=True)
    rumah_sakit = models.ForeignKey(RumahSakit, related_name='dokters', on_delete=models.CASCADE)
    spesialis = models.ForeignKey(Spesialis, related_name='dokters', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('rumah_sakit:dokter_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.nama

class JadwalDokter(models.Model):
    """docstring for JadwalDokter."""
    dokter = models.ForeignKey(Dokter, related_name='jadwal_dokters', on_delete=models.CASCADE)
    senin_masuk = models.TimeField(blank=True, null=True)
    senin_keluar = models.TimeField(blank=True, null=True)
    selasa_masuk = models.TimeField(blank=True, null=True)
    selasa_keluar = models.TimeField(blank=True, null=True)
    rabu_masuk = models.TimeField(blank=True, null=True)
    rabu_keluar = models.TimeField(blank=True, null=True)
    kamis_masuk = models.TimeField(blank=True, null=True)
    kamis_keluar = models.TimeField(blank=True, null=True)
    jumat_masuk = models.TimeField(blank=True, null=True)
    jumat_keluar = models.TimeField(blank=True, null=True)
    sabtu_masuk = models.TimeField(blank=True, null=True)
    sabtu_keluar = models.TimeField(blank=True, null=True)
    minggu_masuk = models.TimeField(blank=True, null=True)
    minggu_keluar = models.TimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('rumah_sakit:jadwal_dokter_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.dokter.nama

class Penyakit(models.Model):
    nama = models.CharField(max_length=100)
    gejala = models.TextField()
    spesialis = models.ForeignKey(Spesialis, related_name='penyakits', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('rumah_sakit:penyakit_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.nama

rumah_sakit/templates/dokter/dokter_confirm_delete.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="container">
    <h1>Delete {{ dokter.nama}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="delete">
        <a href="{% url 'rumah_sakit:dokter_detail' pk=dokter.pk %}" class="btn btn-default">Cancel</a>
    </form>
    </div>
{% endblock %}

rumah_sakit/templates/dokter/dokter_detail.html
{% extends 'base.html' %}

{% block body_block %}

    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h2>Dokter</h2>
            </div>
            <div class="col-lg-4">
                <div class="navbar-right">
                    <a href="{% url 'rumah_sakit:jadwal_dokter_create' %}?id={{ dokter_detail.pk }}">
                        <button class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add Jadwal Dokter</button>
                    </a>
                </div>
            </div>
        </div>
        <hr/>
        <p>Nama : {{ dokter_detail.nama }}</p>
        <p>Jenis Spesialis : {{ dokter_detail.spesialis.jenis_spesialis }}</p>
        <p>Email : {{ dokter_detail.email }}</p>
        <p>Nomor Telepon : {{ dokter_detail.nomor_telepon }}</p>
        <hr/>
        <p>
            <a class="btn btn-warning" href="{% url 'rumah_sakit:dokter_update' pk=dokter_detail.pk %}">Update</a>
            <a class="btn btn-danger" href="{% url 'rumah_sakit:dokter_delete' pk=dokter_detail.pk %}">Delete</a>
        </p>
    </div>
{% endblock %}

rumah_sakit/templates/dokter/dokter_form.html
{% extends 'base.html' %}
{% load widget_tweaks  %}
{% block body_block %}
    <div class="container">
        <h2>Kelolah Dokter</h2>
        <hr/>
        <div class="row">
            <div class="col-lg-8">
                <form method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
{#                    {{ form.as_p }}#}
                    {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.name }}">{{ field.label }}</label>
                            {{ field | add_class:'form-control' }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
            <div class="col-lg-4">
                {% if request.session.role == 'administrator' %}
                    <p class="navbar-right">Spesialis tidak terdaftar? lihat list spesialis<br/>
                        <a href="{% url 'rumah_sakit:spesialis_list' %}"><button class="btn btn-default">List Spesialis</button></a>
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
    <br/>
{% endblock %}

rumah_sakit/templates/dokter/dokter_list.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="container">
     <div class="row">
            <div class="col-lg-8">
                <h1>List Dokter</h1>
            </div>
            <div class="col-lg-4">
                {% if request.session.role == 'administrator' or request.session.role == 'rumah_sakit' %}
                   <div class="navbar-right">
                        <a href="{% url 'rumah_sakit:dokter_create' %}">
                            <button class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add Dokter</button>
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
        <hr/>

        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>Nama Dokter</th>
                    <th>Nama Rumah Sakit</th>
                    <th>Spesialis</th>
                    <th>Email</th>
                    <th>Nomor Telepon</th>
                </tr>
            </thead>
            <tbody>
                {% for foo in dokters %}
                    <tr>
                        <td><a href="detail/{{ foo.pk }}">{{ foo.nama }}</a></td>
                        <td>{{ foo.rumah_sakit.nama }}</td>
                        <td>{{ foo.spesialis.jenis_spesialis }}</td>
                        <td>{{ foo.email }}</td>
                        <td>{{ foo.nomor_telepon }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <br/>
        <div class="text-center">
        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number  }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
        </div>
    </div>
{% endblock %}